name: hostel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:


  flutter:

    sdk: flutter

  # Firebase - REMOVE DUPLICATES
  video_player: ^2.8.2
  device_frame: ^1.4.0
  firebase_core: ^2.28.0  # Use this version for better compatibility
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.18.4

  firebase_storage: ^11.0.0
  device_info_plus: ^10.1.0
  geolocator: ^12.0.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.2


  image_picker: ^1.0.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.5

  # Other dependencies

  font_awesome_flutter: ^10.12.0
  cupertino_icons: ^1.0.8
  intl: 0.20.2
  local_auth: ^2.1.8
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dormace.png"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/service_account.json

 